### ISSUE TITLE
https://api.berkshelf.com down?

### ISSUE THREAD

**Issue by adamdunkley** [berkshelf/api.berkshelf.com#1]
I know this probably isn't the place for it, but I couldn't think of anything better. I was just trying out Berkshelf 3 and wanted to get up and running quickly (so am using the opscode cookbooks) but it seems that https://api.berkshelf.com is down. Or am I just being stupid? Berkshelf just seems to hang …

**Comment by meylor** [comment]
@sethvargo is https://api.berkshelf.com down again? I'm getting a NoSolutionError

````
Fetching cookbook index from https://api.berkshelf.com...
ERROR: Berkshelf::NoSolutionError: Berkshelf::NoSolutionError
```

**Comment by cwebberOps** [comment]
@meylor api.berkshelf.com is part of Chef Supermarket and is currently up. A no solution error means that the depsolver couldn't come up with a set of cookbooks that met all of the version constraints.
